<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhimSeeder extends Seeder
{
    public function run(): void
    {
        $phims = [
            [
                'ten_phim'      => 'Địa Đạo: Mặt Trời Trong Bóng Tối',
                'dao_dien'      => 'Bùi Thạc Chuyên',
                'dien_vien'     =>  'Thái Hòa; Quang Tuấn; Diễm Hằng Lamoon; Anh Tú Wilson; Hồ Thu Anh',
                'hinh_anh'      => 'https://cdn2.tuoitre.vn/zoom/700_438/471584752817336320/2025/3/5/main-1-social-17411985365361565317853-86-0-1336-2000-crop-1741198587688126802165.jpg',
                'quoc_gia'      => 'Việt Nam',
                'nha_san_xuat'  =>  'Nhà sản xuất Nguyễn Trí Viễn',
                'trailer'       => 'https://www.youtube.com/embed/xh6IDHjvytU?si=dTUhWz3bcqFJ2Jod',
                'ngay_phat_hanh' => '2025-04-04',
                'ngon_ngu'      => 'Tiếng Việt - Phụ đề Tiếng Anh',
                'the_loai'      => 'Lịch sử, Chiến tranh',
                'thoi_luong'    => '128',
                'noi_dung'      => 'Địa Đạo: Mặt Trời Trong Bóng Tối là dự án điện ảnh kỷ niệm 50 năm hòa bình thống nhất đất nước, dự kiến khởi chiếu 30.04.2025. Phim do đạo diễn Bùi Thạc Chuyên cầm trịch, với sự tham gia của dàn diễn viên thực lực - Thái Hòa, Quang Tuấn và diễn viên trẻ Hồ Thu Anh. Vào năm 1967, chiến tranh Việt Nam ngày càng khốc liệt. Đội du kích 21 người do BẢY THEO chỉ huy tại căn cứ Bình An Đông trở thành mục tiêu mà quân đội Mỹ TÌM VÀ DIỆT số 1 khi nhận nhiệm vụ bằng mọi giá phải bảo vệ một nhóm thông tin tình báo chiến lược mới đến ẩn náu tại căn cứ. Các cuộc liên lạc vô tuyến điện từ với nhóm tình báo bị quân đội Mỹ phát hiện và định vị, lấy đi lợi thế duy nhất của đội du kích là sự vô hình trong hệ thống địa đạo rộng khắp, phức tạp và bí ẩn. Bộ phim là những câu chuyện đan xen giữa tình đồng đội, tình yêu và khát khao sống ở những người lính. Trên hết, vẫn là nghĩa vụ và sự hi sinh vì Tổ Quốc. Đạo diễn Bùi Thạc Chuyên nung nấu 10 năm trời để chuẩn bị cho phim điện ảnh Địa Đạo, đem câu chuyện huyền thoại về nhân dân miền Nam tài trí thông minh và tinh thần yêu nước ngoan cường ngày ấy lên màn ảnh rộng. Lịch sử đã chứng minh, dẫu cho trên đầu là bom rơi đạn nổ, dưới hầm là không khí đặc quánh đến hít thở cũng khó khăn, chỉ cần trong tim mỗi người chiến sĩ luôn hướng đến ánh sáng tự do của một dân tộc tự do trong tương lai, họ sẽ kiên trì đứng vững mà chiến đấu. Như có mặt trời trong bóng tối luôn soi sáng dẫn đường.',
                'tinh_trang'    => 2,
            ],
            [
                'ten_phim'      => 'Lật Mặt 8: Vòng Tay Nắng',
                'dao_dien'      => 'Lý Hải',
                'dien_vien'     => 'Quốc Cường; Huy Khánh; Trần Kim Hải; Trúc Anh',
                'hinh_anh'      => 'https://image-worker.momocdn.net/img/77210013985876184-lm81.png?size=M&referer=cinema.momocdn.net',
                'quoc_gia'      => 'Việt Nam',
                'nha_san_xuat'  => 'Hãng phim Lý Hải Production',
                'trailer'       => 'https://www.youtube.com/embed/W_0AMP9yO1w?si=wkt6Dg7fNWqE4tJH',
                'ngay_phat_hanh' => '2025-04-25',
                'ngon_ngu'      => 'Tiếng Việt',
                'the_loai'      => 'Tâm lý, Hành động, Gia đình',
                'thoi_luong'    => '120',
                'noi_dung'      => 'Lật Mặt 8: Vòng Tay Nắng kể về sự khác biệt quan điểm giữa ba thế hệ ông bà cha mẹ con cháu. Ai cũng đúng ở góc nhìn của mình nhưng đứng trước hoài bão của tuổi trẻ, cuối cùng thì ai sẽ là người phải nghe theo người còn lại? Và nếu ước mơ của những đứa trẻ bị cho là viển vông, thì cơ hội nào và bao giờ tuổi trẻ mới được tự quyết định tương lai của mình?',
                'tinh_trang'    => 0,
            ],
            [
                'ten_phim'      => 'Thám Tử Kiên: Kỳ Án Không Đầu',
                'dao_dien'      => 'Nguyễn Hữu Tuấn',
                'dien_vien'     => 'Kiều Minh Tuấn; Vân Trang; Hứa Vĩ Văn',
                'hinh_anh'      => 'https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/3/image/1800x/71252117777b696995f01934522c402d/t/t/ttk_poster_official_fa_1638x2048px_1_.jpg',
                'quoc_gia'      => 'Việt Nam',
                'nha_san_xuat'  => 'CJ HK Entertainment',
                'trailer'       => 'https://www.youtube.com/embed/QiXNbEKF3U0?si=YMLEGYErpTCOY83u',
                'ngay_phat_hanh' => '2025-04-19',
                'ngon_ngu'      => 'Tiếng Việt',
                'the_loai'      => 'Trinh thám, Hồi hộp, Hài hước',
                'thoi_luong'    => '110',
                'noi_dung'      => 'Thám Tử Kiên là một nhân vật được yêu thích trong tác phẩm điện của ăn khách Người Vợ Cuối Cùng của Victor Vũ, Thám Tử Kiên: Kỳ Không Đầu sẽ là một phim Victor Vũ trở về với thể loại sở trường Kinh Dị - Trinh Thám sau những tác phẩm tình cảm lãng mạn trước đó. Với slogan đầy ám ảnh: “Kẻ chết không siêu thoát, người sống không lối thoát”, Thám Tử Kiên: Kỳ Án Không Đầu ẩn chứa muôn vàn bí ẩn. Một chuỗi án mạng kinh hoàng tại một ngôi làng hẻo lánh - nơi liên tiếp xảy ra tám vụ giết người với cùng một đặc điểm rợn người: tất cả nạn nhân đều không còn đầu.  Thám Tử Kiên phải đối mặt với vụ án khủng khiếp gây hoang mang tột độ cho dân làng. Ai sẽ là nạn nhân tiếp theo trong chuỗi án mạng rùng rợn? Kiên có tìm ra mấu chốt để lần theo dấu vết hung thủ? Thuộc thể loại tâm linh - ly kỳ - phá án, Thám Tử Kiên: Kỳ Án Không Đầu được đạo diễn Victor Vũ kì công nhào nặn, ghi hình tại Tuyên Quang và Cao Bằng cực kì kĩ lưỡng. Dàn diễn viên chính trong phim bao gồm: Quốc Huy vai Thám tử Kiên, Đinh Ngọc Diệp vai Hai Mẫn, Quốc Anh vai Thạc, Anh Phạm vai Tuyết và Minh Anh vai Nga, NSƯT Xuân Trang trong vai Quan Liêm, NSND Mỹ Uyên trong vai Bà Vượng (vợ quan Liêm).',
                'tinh_trang'    => 2,
            ],
            [
                'ten_phim'      => 'Yadang: Ba Mặt Lật Kèo',
                'dao_dien'      => 'Han Jae-rim',
                'dien_vien'     => 'Lee Byung-hun; Yoo Ah-in; Kim Tae-ri',
                'hinh_anh'      => 'https://cdn.galaxycine.vn/media/2025/5/9/yadang-500_1746783491666.jpg',
                'quoc_gia'      => 'Hàn Quốc',
                'nha_san_xuat'  => 'CJ Entertainment',
                'trailer'       => 'https://www.youtube.com/embed/1sfhCvsEHVo?si=RVLD-bnIDtkbs2PH',
                'ngay_phat_hanh' => '2025-05-11',
                'ngon_ngu'      => 'Tiếng Hàn - Phụ đề Tiếng Việt',
                'the_loai'      => 'Tội phạm, Tâm lý, Hành động',
                'thoi_luong'    => '132',
                'noi_dung'      => '"Từ giờ trở đi, bạn là kẻ chỉ điểm của tôi." Là “cầu nối” giữa thế giới ngầm và các cơ quan thực thi pháp luật, những kẻ chỉ điểm chuyên nghiệp được gọi là "yadang" - người cung cấp thông tin bí mật về thế giới ma túy cho các công tố viên và cảnh sát. Khi một kẻ chỉ điểm ma túy “báo tin” về một bữa tiệc có sự tham dự của các VIP nổi tiếng và vô tình vướng vào một âm mưu nguy hiểm, hắn phải làm mọi thứ trong khả năng của mình không chỉ để sống sót,mà còn để phục thù.',
                'tinh_trang'    => 2,
            ],
            [
                'ten_phim'      => 'Until Dawn: Bí Mật Kinh Hoàng',
                'dao_dien'      => 'Mike Flanagan',
                'dien_vien'     => 'Florence Pugh; Finn Wolfhard; Jenna Ortega',
                'hinh_anh'      => 'https://files.betacorp.vn/media%2Fimages%2F2025%2F04%2F18%2Fmv5bzwu4ndy0odktogi3oc00nwe1lwiwymqtnmjizwu3nmzlmdhkxkeyxkfqcgc-v1-142951-180425-22.jpg',
                'quoc_gia'      => 'Mỹ',
                'nha_san_xuat'  => 'Sony Pictures, Blumhouse',
                'trailer'       => 'https://www.youtube.com/embed/JKwMefRG5-I?si=FlTzJWL018T3oxjQ',
                'ngay_phat_hanh' => '2025-10-30',
                'ngon_ngu'      => 'Tiếng Anh - Phụ đề Tiếng Việt',
                'the_loai'      => 'Kinh dị, Giật gân',
                'thoi_luong'    => '118',
                'noi_dung'      => 'Until Dawn/ Until Dawn: Bí Mật Kinh Hoàng diễn ra sau khi em gái Melanie mất tích một cách bí ẩn, Clover cùng bạn bè quyết định vào một thung lũng nơi cuối cùng nhìn thấy em gái để tìm kiếm câu trả lời. Khi lạc vào một khu nhà bỏ hoang, họ bị một kẻ giết người đeo mặt nạ theo dõi và bị sát hại một cách kinh hoàng từng người một... cho đến khi họ tỉnh dậy và phát hiện mình quay ngược lại vào buổi tối đầu tiên.  Bị mắc kẹt trong một vòng lặp thời gian bí ẩn, họ buộc phải sống lại cơn ác mộng đó mỗi đêm, nhưng mỗi lần lại phải đối mặt với những mối đe dọa mới và những cách chết khác nhau, ngày càng đáng sợ hơn. Khi hy vọng dần tắt, nhóm bạn nhận ra họ chỉ còn 13 mạng sống trước khi biến mất mãi mãi. Cách duy nhất để thoát khỏi là sống sót cho đến khi bình minh.',
                'tinh_trang'    => 1,
            ],
            [
                'ten_phim'      => 'Shin Cậu Bé Bút Chì: Bí Ẩn! Học Viện Hoa Lệ Tenkasu',
                'dao_dien'      => 'Wataru Takahashi',
                'dien_vien'     => 'Yumiko Kobayashi; Miki Narahashi',
                'hinh_anh'      => 'https://cdn.galaxycine.vn/media/2025/4/10/crayon-shinchan-the-movie-school-mystery-the-splendid-tenkasu-academy-2_1744271074944.jpg',
                'quoc_gia'      => 'Nhật Bản',
                'nha_san_xuat'  => 'Shin-Ei Animation',
                'trailer'       => 'https://www.youtube.com/embed/2ck-25PYR-o?si=Ij2QoYnbLVrNX-8u',
                'ngay_phat_hanh' => '2025-07-20',
                'ngon_ngu'      => 'Tiếng Nhật - Lồng tiếng/Phụ đề Tiếng Việt',
                'the_loai'      => 'Hoạt hình, Hài, Phiêu lưu',
                'thoi_luong'    => '104',
                'noi_dung'      => 'Phim Shin Cậu Bé Bút Chì: Bí Ẩn! Học Viện Hoa Lệ Tenkasu kể về trải nghiệm học tại Học viện Tenkasu của bé Shin. Shinnosuke và những người bạn của Shin thuộc Đội đặc nhiệm Kasukabe trải qua một tuần ở lại "Học viện Tư nhân Tenkasu Kasukabe" (Học viện Tenkasu). Đây là trường nội trú ưu tú được quản lý bởi một AI hiện đại - Otsmun.  Tất cả các học sinh ban đầu được trao một huy hiệu với 1000 điểm và điểm của các em sẽ được Otsmun tăng hoặc giảm dựa trên hành vi và kết quả học tập của các em. Tuy nhiên, ai đó đã tấn công Kazama. Đội đặc nhiệm Kasukabe hợp lực với chủ tịch hội học sinh bỏ học của trường, Chishio Atsuki, một cựu vận động viên, để thành lập một nhóm thám tử và giải quyết bí ẩn.',
                'tinh_trang'    => 1,
            ],
            [
                'ten_phim'      => 'Biệt Đội Sấm Sét',
                'dao_dien'      => 'Ben Falcone',
                'dien_vien'     => 'Melissa McCarthy; Octavia Spencer',
                'hinh_anh'      => 'https://cdn.galaxycine.vn/media/2025/4/23/thunderbolts-500_1745395912649.jpg',
                'quoc_gia'      => 'Hoa Kỳ',
                'nha_san_xuat'  => 'Netflix, On The Day Productions',
                'trailer'       => 'https://www.youtube.com/embed/AWE9xJ5SL3o?si=D0utw-phx95IxEPm',
                'ngay_phat_hanh' => '2025-05-10',
                'ngon_ngu'      => 'Tiếng Anh - Phụ đề Tiếng Việt',
                'the_loai'      => 'Siêu anh hùng, Hài, Hành động',
                'thoi_luong'    => '106',
                'noi_dung'      => 'Trong một thế giới nơi siêu ác nhân là mối đe dọa thường trực, một nhóm bạn không có siêu năng lực đã chế tạo ra công nghệ để biến mình thành những siêu anh hùng và lập nên Biệt Đội Sấm Sét bảo vệ thành phố.',
                'tinh_trang'    => 2,
            ],
            [
                'ten_phim'      => 'Holy Night: Đội Săn Quỷ',
                'dao_dien'      => 'Takashi Miike',
                'dien_vien'     => 'Takuya Kimura; Masami Nagasawa',
                'hinh_anh'      => 'https://cdn.galaxycine.vn/media/2025/5/6/holy-night-500_1746503995269.jpg',
                'quoc_gia'      => 'Nhật Bản',
                'nha_san_xuat'  => 'Toei Company',
                'trailer'       => 'https://www.youtube.com/embed/Iwg6nQxN51I?si=n1TPGjEG7Wv28ttI',
                'ngay_phat_hanh' => '2025-10-31',
                'ngon_ngu'      => 'Tiếng Nhật - Phụ đề Tiếng Việt',
                'the_loai'      => 'Kinh dị, Giả tưởng, Hành động',
                'thoi_luong'    => '118',
                'noi_dung'      => 'Vào đêm Giáng Sinh, một nhóm thợ săn quỷ chuyên nghiệp phải chiến đấu với thế lực bóng tối cổ xưa đang trỗi dậy tại Tokyo. Những nghi thức cổ đại, linh hồn lang thang và sự hy sinh sẽ quyết định số phận thành phố.',
                'tinh_trang'    => 2,
            ],
            [
                'ten_phim'      => 'Quái Thú Đại Náo Sở Thú',
                'dao_dien'      => 'Brad Peyton',
                'dien_vien'     => 'Dwayne Johnson; Naomie Harris',
                'hinh_anh'      => 'https://cdn.galaxycine.vn/media/2025/4/16/quai-thu-500_1744775258641.jpg',
                'quoc_gia'      => 'Hoa Kỳ',
                'nha_san_xuat'  => 'Warner Bros., New Line Cinema',
                'trailer'       => 'https://www.youtube.com/embed/IrEin0s_0Ik?si=ABnC-rDFyrrkQgF2',
                'ngay_phat_hanh' => '2025-09-12',
                'ngon_ngu'      => 'Tiếng Anh - Phụ đề Tiếng Việt',
                'the_loai'      => 'Hành động, Khoa học viễn tưởng',
                'thoi_luong'    => '101',
                'noi_dung'      => 'Một thử nghiệm di truyền thất bại khiến nhiều loài động vật tại sở thú đột biến thành quái thú khổng lồ. Một nhà sinh vật học và đội đặc nhiệm phải ngăn chặn thảm họa khi chúng thoát ra và tấn công thành phố.',
                'tinh_trang'    => 1,
            ],
            [
                'ten_phim'      => 'Phim Điện Ảnh Doraemon: Nobita Và Cuộc Phiêu Lưu Vào Thế Giới Trong Tranh',
                'dao_dien'      => 'Kazuaki Imai',
                'dien_vien'     => 'Wasabi Mizuta; Megumi Ōhara',
                'hinh_anh'      => 'https://cdn.galaxycine.vn/media/2025/5/9/doraemon-the-movie-nobitas-art-world-tales-1_1746800200069.jpg',
                'quoc_gia'      => 'Nhật Bản',
                'nha_san_xuat'  => 'Shin-Ei Animation, TV Asahi',
                'trailer'       => 'https://www.youtube.com/embed/nDR_9NCMIYk?si=QZ032Uf1Ki5bJd9C',
                'ngay_phat_hanh' => '2025-12-20',
                'ngon_ngu'      => 'Tiếng Nhật - Lồng tiếng/Phụ đề Tiếng Việt',
                'the_loai'      => 'Hoạt hình, Phiêu lưu, Gia đình',
                'thoi_luong'    => '99',
                'noi_dung'      => 'Doraemon sử dụng bảo bối đưa nhóm bạn vào một thế giới bên trong tranh vẽ. Tại đây, họ gặp những nhân vật kỳ bí và phải giải mã bí ẩn cổ xưa để trở về thế giới thật, đồng thời cứu lấy thế giới tranh khỏi sự hủy diệt.',
                'tinh_trang'    => 2,
            ],
            [
                'ten_phim'      => 'Dế Mèn: Cuộc Phiêu Lưu Tới Xóm Lầy Lội',
                'dao_dien'      => 'Trần Vũ Minh',
                'dien_vien'     => 'Lồng tiếng bởi các nghệ sĩ Việt: Xuân Bắc, Tự Long',
                'hinh_anh'      => 'https://cdn.galaxycine.vn/media/2025/5/6/de-men-500_1746513868460.jpg',
                'quoc_gia'      => 'Việt Nam',
                'nha_san_xuat'  => 'Hãng phim hoạt hình Việt Nam',
                'trailer'       => 'https://www.youtube.com/embed/Vwwsh0QxwIs?si=wctix0qqNzXst_ww',
                'ngay_phat_hanh' => '2025-06-01',
                'ngon_ngu'      => 'Tiếng Việt',
                'the_loai'      => 'Hoạt hình, Phiêu lưu, Hài',
                'thoi_luong'    => '95',
                'noi_dung'      => 'Dựa trên cảm hứng từ “Dế Mèn Phiêu Lưu Ký”, bộ phim là hành trình phiêu lưu hài hước và xúc động của Dế Mèn khi lạc đến vùng đất Xóm Lầy Lội và kết bạn với các loài sinh vật kỳ quái, đồng thời học được những bài học quý giá về lòng dũng cảm và tình bạn.',
                'tinh_trang'    => 1,
            ],



        ];
        DB::table('phims')->truncate();
        DB::table('phims')->delete();
        DB::table('phims')->insert($phims);
    }
}
